// Importing necessary types and components from Next.js and Google Fonts
import type { Metadata } from "next"; // Importing the Metadata type for defining metadata
import { Geist, Geist_Mono } from "next/font/google"; // Importing Geist and Geist_Mono font components from Google Fonts
import "./globals.css"; // Importing global CSS styles

// Initializing the Geist font with specific variable and subsets
const geistSans = Geist({
  variable: "--font-geist-sans", // CSS variable for the sans font
  subsets: ["latin"], // Specifying the character subsets to include
});

// Initializing the Geist_Mono font with specific variable and subsets
const geistMono = Geist_Mono({
  variable: "--font-geist-mono", // CSS variable for the mono font
  subsets: ["latin"], // Specifying the character subsets to include
});

// Defining the metadata for the application
export const metadata: Metadata = {
  title: "Create Next App", // Title of the application
  description: "Generated by create next app", // Description of the application
};

// Defining the RootLayout component which wraps the children components
export default function RootLayout({
  children, // Accepting children as a prop
}: Readonly<{
  children: React.ReactNode; // Defining the type for children as React nodes
}>) {
  return (
    <html lang="en"> {/* Setting the language attribute for the HTML document */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} // Applying the font variables and enabling antialiasing for smoother text
      >
        {children} {/* Rendering the children components inside the body */}
      </body>
    </html>
  );
}
