FROM rocm/pytorch:rocm6.4.2_ubuntu24.04_py3.12_pytorch_release_2.6.0

RUN apt-get update
RUN apt-get install -y libopenmpi-dev openmpi-bin
RUN apt-get install -y libevdev-dev && ldconfig
RUN pip install gymnasium stable_baselines3 mpi4py
CMD ["python", "/app/main.py"]