FROM rocm/dev-ubuntu-22.04:6.4.2-complete

RUN apt-get update && \
    apt-get install -y python3 python3-pip libopenmpi-dev openmpi-bin libevdev-dev gcc-12 g++-12 && \
    ldconfig

RUN rm -f /usr/lib/x86_64-linux-gnu/libstdc++.so.6 && \
    ln -s /usr/lib/gcc/x86_64-linux-gnu/12/libstdc++.so /usr/lib/x86_64-linux-gnu/libstdc++.so.6

RUN ln -s /opt/rocm/lib/libamd_comgr.so.3 /opt/rocm/lib/libamd_comgr.2

ENV LLVM_PATH=/opt/rocm/llvm
ENV LD_LIBRARY_PATH=/opt/rocm/lib:/opt/rocm/lib64:$LD_LIBRARY_PATH
ENV PATH=/usr/lib/gcc-12:$PATH

RUN pip install jax[rocm] gymnasium stable_baselines3 sbx-rl mpi4py optuna tensorboard

CMD ["python3", "/app/main.py"]
