FROM rocm/jax:rocm6.4.2-jax0.4.35-py3.12

RUN apt-get update
# RUN apt-get install -y software-properties-common && \
#     add-apt-repository ppa:ubuntu-toolchain-r/test && \
#     apt-get update && apt-get install -y gcc-13 g++-13 libstdc++6
RUN apt-get install -y libopenmpi-dev openmpi-bin libevdev-dev && \
    ldconfig

# RUN ln -s /opt/rocm/lib/libamd_comgr.so.3 /opt/rocm/lib/libamd_comgr.so.2

# ENV LLVM_PATH=/opt/rocm/llvm
# ENV LD_LIBRARY_PATH=/opt/rocm/lib:/opt/rocm/lib64:$LD_LIBRARY_PATH
# ENV PATH=/usr/lib/gcc-12:$PATH

RUN pip install jaxlib==0.4.35 gymnasium sbx-rl mpi4py optuna tensorboard

CMD ["python3", "/app/main.py"]
